=== SoweluAvanzo/DAO-ML_to_Solidity/data/XSD_DAO_ML.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid Studio (https://www.liquid-technologies.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <!-- Global Type Definitions -->
  <xs:complexType name="relation">
    <xs:simpleContent>
      <xs:extension base="xs:IDREFS">
        <xs:anyAttribute namespace="##any" processContents="skip" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
<!-- DAO-ML Diagram -->
<xs:element name="DAO-ML_diagram">
<xs:complexType>
<xs:sequence>
<!-- DAO Element -->
<xs:element name="DAO" minOccurs="1" maxOccurs="unbounded">
<xs:complexType>
<xs:choice minOccurs="0" maxOccurs="unbounded">
<!-- Role Element -->
<xs:element name="Role" minOccurs="0" maxOccurs="unbounded">
<xs:complexType>
<xs:choice minOccurs="0" maxOccurs="unbounded">
<xs:element name="is_controlled_by" type="relation" minOccurs="0" maxOccurs="unbounded" />
<xs:element name="associated_to" type="relation" minOccurs="0" maxOccurs="unbounded" />
<xs:element name="aggregates" type="relation" minOccurs="0" maxOccurs="unbounded" />
<xs:element name="federates_into" type="relation" minOccurs="0" maxOccurs="unbounded" />
</xs:choice>
<xs:attribute name="role_ID" type="xs:ID" use="required" />
<xs:attribute name="role_name" type="xs:string" use="required" />
<xs:attribute name="role_assignment_method" type="xs:string" use="optional" />
<xs:attribute name="n_agent_min" type="xs:int" use="optional" />
<xs:attribute name="n_agent_max" type="xs:int" use="optional" />
<xs:attribute name="agent_type" use="optional">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="human" />
<xs:enumeration value="autonomous_agent" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
<xs:attribute name="aggregation_level" type="xs:int" use="required"/>
<xs:attribute name="federation_level" type="xs:int" use="required"/>
<xs:anyAttribute namespace="##any" processContents="skip"/>
</xs:complexType>
</xs:element>
<!-- Committee Element -->
<xs:element name="Committee" minOccurs="0" maxOccurs="unbounded">
<xs:complexType>
<xs:choice minOccurs="0" maxOccurs="unbounded">
<xs:element name="is_controlled_by" type="relation" minOccurs="0" maxOccurs="unbounded" />
<xs:element name="associated_to" type="relation" minOccurs="0" maxOccurs="unbounded" />
<xs:element name="aggregates" type="relation" minOccurs="0" maxOccurs="unbounded" />
<xs:element name="federates_into" type="relation" minOccurs="0" maxOccurs="unbounded" />
</xs:choice>
<xs:attribute name="committee_ID" type="xs:ID" use="required" />
<xs:attribute name="committee_description" type="xs:string" use="required"/>
<xs:attribute name="voting_condition" type="xs:string" use="optional"/>
<xs:attribute name="proposal_condition" type="xs:string" use="optional"/>
<xs:attribute name="decision_making_method" type="xs:string" use="optional"/>
<xs:attribute name="aggregation_level" type="xs:int"/>
<xs:attribute name="federation_level" type="xs:int"/>
<xs:anyAttribute namespace="##any" processContents="skip"/>
</xs:complexType>
</xs:element>
  <!-- GovernanceArea Element -->
<xs:element name="GovernanceArea" minOccurs="0" maxOccurs="unbounded">
<xs:complexType>
<xs:attribute name="gov_area_ID" type="xs:ID" use="required"/>
<xs:attribute name="gov_area_description" type="xs:string" use="required" />
<xs:attribute name="implementation" use="required">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="on-chain"/>
<xs:enumeration value="hybrid"/>
<xs:enumeration value="off-chain"/>
</xs:restriction>
</xs:simpleType>
</xs:attribute>
<xs:anyAttribute namespace="##any" processContents="skip"/>
</xs:complexType>
</xs:element>
<!-- Permission Element -->
<xs:element name="Permission" minOccurs="0" maxOccurs="unbounded">
<xs:complexType>
<xs:attribute name="permission_ID" type="xs:ID" use="required" />
<xs:attribute name="allowed_action" type="xs:string" use="required" />
<xs:attribute name="permission_type" use="required">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="structural" />
<xs:enumeration value="strategic" />
<xs:enumeration value="operational" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
<xs:attribute name="ref_gov_area" type="xs:IDREF" use="optional" />
<xs:anyAttribute namespace="##any" processContents="skip"/>
</xs:complexType>
</xs:element>
</xs:choice>
<xs:attribute name="DAO_ID" type="xs:ID" use="required" />
<xs:attribute name="DAO_name" type="xs:string" use="required" />
<xs:attribute name="mission_statement" type="xs:string" />
<xs:attribute name="hierarchical_inheritance" type="xs:boolean" use="required" />
<xs:anyAttribute namespace="##any" processContents="skip"/>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="name" type="xs:string" use="required" />
<xs:attribute name="uniqueID" type="xs:ID" use="required" />
<xs:anyAttribute namespace="##any" processContents="skip"/>
</xs:complexType>
</xs:element>
</xs:schema>

=== SoweluAvanzo/DAO-ML_to_Solidity/data/tests/t_dao_1.xml
<DAO-ML_diagram name="Test 1" 
    uniqueID="dao_a10f2b1a_ee5b_4b99_b531_a704edb909ca" 
    xsi:noNamespaceSchemaLocation="XSD_DAO_ML.xsd" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" x="0" y="0" width="0" height="0"
>

	<DAO 
        DAO_ID="dao_01234567_0123_3210_9876_9876543210fg"
        DAO_name="DAO 1"
        mission_statement="Testing a single DAO"
        hierarchical_inheritance="false"
        x="403.51017869275967" y="405.68447847623025" width="1232.5552658266886" height="777.1958192318468"
    >

        <Role
            role_ID="dao_00000000_0000_0000_bbb1_001100220033"
            role_name="R_1_in_C_1"
            n_agent_min="0" n_agent_max="0" agent_type="human"
            aggregation_level="0" federation_level="0"
            x="495.556296307872" y="1001.9362619875442" width="50" height="80"
            >
            <federates_into _id="dao_778143a6_28ca_4964_beae_e04a5edd8c76">dao_00000000_0000_0000_bbb3_001100220033</federates_into>
            <associated_to _id="dao_1cadc62e_7bfe_4903_9a92_3f34b5c75ffd">dao_00000000_0000_0000_bbb3_001100220033</associated_to>
            <aggregates _id="dao_63c4cc53_1a33_4eaa_96a7_bc275b2473f5">dao_88e4a6f9_b82e_4227_b8bb_3c1065471ace</aggregates>
        </Role>

        
		<Role 
            role_ID="dao_00000000_0000_0000_bbb2_001100220033"
            role_name="R_2_in_C_1"
            n_agent_min="0" n_agent_max="0"
            agent_type="human"
            aggregation_level="0" federation_level="0"
            x="192.35590138907529" y="361.7863776984612" width="50" height="80"
        >
			<federates_into _id="dao_a61651aa_50a0_4950_b58e_6e70d7f5f809">dao_00000000_0000_0000_ccc1_001100220033</federates_into>
			<aggregates _id="dao_238729db_7c8d_4812_8def_c0820593a680">dao_00000000_0000_0000_bbb3_001100220033</aggregates>
			<associated_to _id="dao_0ee5c19f_86a5_42b8_bd77_24e616a0b4bd">dao_ce969c91_5e5e_4922_9302_6084a778fb95</associated_to>
		</Role>
        
		<Role 
            role_ID="dao_00000000_0000_0000_bbb3_001100220033"
            role_name="Super_Role"
            n_agent_min="0" n_agent_max="0"
            agent_type="human"
            aggregation_level="0" federation_level="0"
            x="192.35590138907529" y="361.7863776984612" width="50" height="80"
        >
			<federates_into _id="dao_a61651aa_50a0_4950_b58e_6e70d7f5f809">dao_00000000_0000_0000_ccc1_001100220033</federates_into>
			<associated_to _id="dao_0ee5c19f_86a5_42b8_bd77_24e616a0b4bd">dao_ce969c91_5e5e_4922_9302_6084a778fb95</associated_to>
		</Role>


        <Committee
            committee_ID="dao_00000000_0000_0000_ccc1_001100220033"
            committee_description="Committee 1"
            aggregation_level="0" federation_level="0" x="748.5821811320366" y="97.83346679343697" width="112" height="49">
			<aggregates _id="dao_f81a6293_ba86_436c_9f96_501410200f29">dao_88e4a6f9_b82e_4227_b8bb_3c1065471ace</aggregates>
			<is_controlled_by _id="dao_bae263c0_f04c_4570_a3b9_9ca8a9430773">dao_88e4a6f9_b82e_4227_b8bb_3c1065471ace</is_controlled_by>
			<associated_to _id="dao_b04c6b0f_d3b0_4aba_ae68_950680f739b9">dao_ce969c91_5e5e_4922_9302_6084a778fb95</associated_to>
		</Committee>

        <Permission
            permission_ID="dao_ce969c91_5e5e_4922_9302_6084a778fb95"
            allowed_action="Permission minor"
            permission_type="strategic"
            ref_gov_area="dao_00000000_0000_0000_ggg1_001100220033"
            x="40.687710798292635" y="419.28101732639414" width="91" height="49"
        />


        <Committee committee_ID="dao_88e4a6f9_b82e_4227_b8bb_3c1065471ace"
            committee_description="Comm super-aggregate"
            aggregation_level="0" federation_level="0" x="393.4130467328496" y="368.08973270360997" width="112" height="49">
			<aggregates _id="dao_ef1657dc_4c5a_4187_8cbc_eb4d0f624a71">dao_381786b9_effe_4564_9200_cf2e74ef3c1f</aggregates>
			<is_controlled_by _id="dao_bae263c0_f04c_4570_a3b9_9ca8a9430773">dao_381786b9_effe_4564_9200_cf2e74ef3c1f</is_controlled_by>
			<associated_to _id="dao_c6d8a55f_626e_49d7_8af3_67c657dd28ea">dao_0ab24a59_0b5b_485d_9976_00e0cf5a0af4</associated_to>
		</Committee>
        <Permission
            permission_ID="dao_0ab24a59_0b5b_485d_9976_00e0cf5a0af4"
            allowed_action="Permission over everything"
            permission_type="operational"
            ref_gov_area="dao_00000000_0000_0000_ggg1_001100220033"
            x="375.5199425537032" y="286.50008724834646" width="91" height="49"
        />

		<GovernanceArea
            gov_area_ID="dao_00000000_0000_0000_ggg1_001100220033"
            gov_area_description="Governance Area 1"
            implementation="off-chain"
            x="37.343464189043644" y="548.9801915434043" width="172.8" height="222" />
		
	</DAO>
</DAO-ML_diagram>

=== SoweluAvanzo/DAO-ML_to_Solidity/data/example.xml
<DAO-ML_diagram name="Group Currency DAO Diagram" uniqueID="GCDAOdiagram" xsi:noNamespaceSchemaLocation="XSD_DAO_ML.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" x="0" y="0" width="0" height="0">
	<DAO DAO_ID="GCDAO" DAO_name="Group Currency DAO" mission_statement="Managing the governance of Group Currencies in the Circles UBI system." hierarchical_inheritance="0" x="-656.9034974661294" y="-389.48950348622895" width="1822.775688030754" height="917.369803643616">
		<Role role_ID="GroupMember" role_name="Group Member" n_agent_min="0" n_agent_max="0" agent_type="human" aggregation_level="0" federation_level="0" x="844.093100033392" y="361.3023926542953" width="50" height="80">
			<federates_into _id="02fd4f60-a06c-406b-9ea8-4512cfef67ca">GeneralAssembly</federates_into>
			<associated_to _id="832f11ba-ced4-4a7c-bab3-8e6105ba9679">propose_service_provision</associated_to>
			<associated_to _id="26cde596-9217-4032-9cc9-5767e6bb635f">update_user_profile</associated_to>
			<associated_to _id="d780c8ba-9935-4a64-9b94-371ebf5585a8">funding_request_submission</associated_to>
		</Role>
		<Role role_ID="ActiveMember" role_name="Active Member" n_agent_min="3" n_agent_max="15" agent_type="human" aggregation_level="1" federation_level="0" x="1139.91587109739" y="73.54162143526796" width="50" height="80">
			<federates_into _id="dc3c9397-8aef-471b-b6d0-cb11a4615987">CommunityCouncil</federates_into>
			<federates_into _id="8c8ce998-bcf5-43f5-9ec0-2d536b84b853">TechnicalCouncil</federates_into>
		</Role>
		<Committee committee_ID="EconomicCouncil" committee_description="Economic Council" decision_making_method="lazy_consensus" aggregation_level="0" federation_level="1" x="474.7763550776228" y="138.9498403167566" width="112" height="49">
			<associated_to _id="10d575ad-6590-43ee-8fdd-58a873a6f8e0">add_remove_allowed_collateral_type</associated_to>
			<is_controlled_by _id="c0e4f039-a734-4eb5-9b08-ccefc7717f0e">CommunityCouncil</is_controlled_by>
		</Committee>
		<Committee committee_ID="CommunityCouncil" committee_description="Community Council" decision_making_method="quadratic_voting" aggregation_level="0" federation_level="1" x="812.5942897240346" y="255.06489047204187" width="119" height="49">
			<associated_to _id="b51dadd5-9e3b-4086-a4a9-abf8665e0d7e">set_contribution_attestation</associated_to>
			<associated_to _id="c773545f-6c58-4ab3-80ac-2165d5f5e85d">set_membership_requirements</associated_to>
			<associated_to _id="849e1408-9fcd-4146-b1cd-e2ed869865b0">include_exclude_group_members</associated_to>
			<is_controlled_by _id="e856ce08-9e85-4517-af66-2e6f355a3c7a">TechnicalCouncil</is_controlled_by>
		</Committee>
		<Committee committee_ID="TechnicalCouncil" committee_description="Technical Council" decision_making_method="optimistic_governance" aggregation_level="0" federation_level="1" x="1119.0356039071776" y="272.2036610973033" width="154" height="49">
			<associated_to _id="4382e651-7ff4-499a-8843-f36fc73bd80c">upgrade_Group_Currency_smart_contracts</associated_to>
			<associated_to _id="54097e0c-1697-4208-9d2f-9d4c3b26af90">member_data_management</associated_to>
			<associated_to _id="0f6b25de-00fc-4cdd-9f0f-a5bd51f37a0f">suspension_of_the_group_currency</associated_to>
			<associated_to _id="2bf8f78e-057b-4ea6-9e62-461ec9994b27">upgrade_DAO_smart_contracts</associated_to>
		</Committee>
		<GovernanceArea gov_area_ID="ServiceProvision" gov_area_description="Service Provision" implementation="hybrid" x="792.9984377919842" y="597.6370950841972" width="218.4" height="222" />
		<GovernanceArea gov_area_ID="GroupMembership" gov_area_description="Group Membership" implementation="on-chain" x="1491.2410491591338" y="420.6467151953609" width="226.8" height="276" />
		<GovernanceArea gov_area_ID="DAOUpgrades" gov_area_description="DAO Upgrades" implementation="on-chain" x="1416.4771688651738" y="203.04428757662757" width="319.2" height="168" />
		<GovernanceArea gov_area_ID="Attestations" gov_area_description="Attestations" implementation="on-chain" x="225.02306853007815" y="761.1555791744638" width="120" height="60" />
		<GovernanceArea gov_area_ID="TreasuryManagement" gov_area_description="Treasury Management" implementation="on-chain" x="30.01900943143794" y="319.05449723648303" width="302.4" height="384" />
		<GovernanceArea gov_area_ID="EmergencyResponse" gov_area_description="Emergency Response" implementation="hybrid" x="27.4821632285948" y="760.6227991215272" width="172.8" height="60" />
		<Committee committee_ID="GeneralAssembly" committee_description="General Assembly" decision_making_method="simple_majority" aggregation_level="0" federation_level="1" x="570.3646983724275" y="405.02514326695797" width="112" height="49">
			<associated_to _id="48b30299-acb3-4490-9133-652f3c7c9daa">activate_suspend_service_provision</associated_to>
			<associated_to _id="8aaa3d0a-aafb-472c-9421-8c916a2664a0">evaluate_service_provision</associated_to>
			<is_controlled_by _id="fc0e088e-7299-44a0-8820-546f3bd75cb2">EconomicCouncil</is_controlled_by>
			<is_controlled_by _id="c0b8b2c4-4424-4095-8f09-e4633de15ef3">TreasuryManager</is_controlled_by>
		</Committee>
		<Role role_ID="TreasuryManager" role_name="Treasury Manager" n_agent_min="0" n_agent_max="0" agent_type="human" aggregation_level="0" federation_level="0" x="111.18051749923714" y="119.35065567173295" width="50" height="80">
			<federates_into _id="623b0f05-481c-465f-aff3-0796e2cb5d1c">EconomicCouncil</federates_into>
			<aggregates _id="67d971e5-a5ff-40bc-95ca-e84df72bf9bc">ActiveMember</aggregates>
			<associated_to _id="12eec065-f626-4f87-a7fc-6db20dc0e0fc">funding_request_assessment</associated_to>
			<associated_to _id="d683a9b1-9a24-47d6-b754-168e3fe89906">set_limits_to_group_currency_minting</associated_to>
			<is_controlled_by _id="43050b2a-56dc-4880-a595-b1516194a2b1">EconomicCouncil</is_controlled_by>
		</Role>
		<Permission permission_ID="evaluate_service_provision" allowed_action="evaluate service provision" permission_type="strategic" ref_gov_area="ServiceProvision" x="18.2" y="40" width="182" height="49" />
		<Permission permission_ID="activate_suspend_service_provision" allowed_action="suspend service provision" permission_type="strategic" ref_gov_area="ServiceProvision" x="18.2" y="94" width="175" height="49" />
		<Permission permission_ID="propose_service_provision" allowed_action="propose service provision" permission_type="operational" ref_gov_area="ServiceProvision" x="18.2" y="148" width="175" height="49" />
		<Permission permission_ID="include_exclude_group_members" allowed_action="include/exclude members" permission_type="structural" ref_gov_area="GroupMembership" x="18.900000000000002" y="40" width="161" height="49" />
		<Permission permission_ID="member_data_management" allowed_action="member data management" permission_type="structural" ref_gov_area="GroupMembership" x="18.900000000000002" y="94" width="154" height="49" />
		<Permission permission_ID="set_membership_requirements" allowed_action="set membership requirements" permission_type="structural" ref_gov_area="GroupMembership" x="18.900000000000002" y="148" width="189" height="49" />
		<Permission permission_ID="update_user_profile" allowed_action="update user profile" permission_type="structural" ref_gov_area="GroupMembership" x="18.900000000000002" y="202" width="133" height="49" />
		<Permission permission_ID="upgrade_Group_Currency_smart_contracts" allowed_action="upgrade Group Currency smart contracts" permission_type="structural" ref_gov_area="DAOUpgrades" x="26.6" y="40" width="266" height="49" />
		<Permission permission_ID="upgrade_DAO_smart_contracts" allowed_action="upgrade DAO smart contracts" permission_type="structural" ref_gov_area="DAOUpgrades" x="26.6" y="94" width="189" height="49" />
		<Permission permission_ID="set_limits_to_group_currency_minting" allowed_action="set limits to group currency minting" permission_type="strategic" ref_gov_area="TreasuryManagement" x="25.200000000000003" y="40" width="252" height="49" />
		<Permission permission_ID="funding_request_assessment" allowed_action="funding request assessment" permission_type="strategic" ref_gov_area="TreasuryManagement" x="25.200000000000003" y="94" width="182" height="49" />
		<Permission permission_ID="set_contribution_attestation" allowed_action="set contribution attestation" permission_type="structural" ref_gov_area="TreasuryManagement" x="25.200000000000003" y="148" width="196" height="49" />
		<Permission permission_ID="add_remove_allowed_collateral_type" allowed_action="add/remove allowed collateral type" permission_type="strategic" ref_gov_area="TreasuryManagement" x="25.200000000000003" y="202" width="238" height="49" />
		<Permission permission_ID="funding_request_submission" allowed_action="funding request submission" permission_type="operational" ref_gov_area="TreasuryManagement" x="25.200000000000003" y="256" width="182" height="49" />
		<Permission permission_ID="suspension_of_the_group_currency" allowed_action="suspension of the Group Currency" permission_type="structural" ref_gov_area="TreasuryManagement" x="25.200000000000003" y="310" width="224" height="49" />
	</DAO>
	<DAO DAO_ID="4088068f-1775-4e3d-be08-8f17954e0a84" DAO_name="Travelhive DAO" mission_statement="manage the Travelhive ecosystem governance" hierarchical_inheritance="false" x="1256.6551276928847" y="-165.23243354427507" width="613.5658847750393" height="370.2453490757971">

		<Permission permission_ID="1e7aed29-b7bc-4c7a-9824-2dee4abca6c5" allowed_action="create new DDMO" permission_type="strategic" ref_gov_area="4088068f-1775-4e3d-be08-8f17954e0a84" x="463.51478455227885" y="94.06910001027121" width="105" height="49" />
		<Permission permission_ID="1d5a853f-38de-4ed4-827c-ea7a1b427f5e" allowed_action="modify salary distribution policy" permission_type="operational" ref_gov_area="4088068f-1775-4e3d-be08-8f17954e0a84" x="260.13807045094495" y="188.3619401845261" width="231" height="49" />
	</DAO>
</DAO-ML_diagram>
